winget install --id Microsoft.VisualStudio.2022.Community
winget install --id Git.Git
winget install --id GitHub.cli
winget install --id Microsoft.VisualStudioCode
winget install --id SumatraPDF.SumatraPDF
winget install --id 7zip.7zip
winget install --id Rufus.Rufus
winget install --id AutoHotkey.AutoHotkey
winget install --id GNU.Emacs
winget install --id Transmission.Transmission
winget install --id EclipseAdoptium.Temurin.21.JDK
winget install --id calibre.calibre
winget install --id VideoLAN.VLC
winget install --id Google.Chrome
winget install --id Mozilla.Firefox.DeveloperEdition
winget install --id KeePassXCTeam.KeePassXC
winget install --id JetBrains.Toolbox
winget install --id UniKey.UniKey
winget install --id CoreyButler.NVMforWindows
